# Generated by Django 5.0.1 on 2024-02-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.RemoveField(
            model_name='ordersmodel',
            name='product',
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=999999.99, max_digits=8),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordersmodel',
            name='product',
            field=models.ManyToManyField(to='market.productsmodel'),
        ),
    ]
