# Generated by Django 5.0.1 on 2024-02-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersmodel',
            name='product',
        ),
        migrations.AddField(
            model_name='ordersmodel',
            name='product',
            field=models.ManyToManyField(to='market.productsmodel'),
        ),
    ]
