# Generated by Django 5.0.1 on 2024-02-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_remove_ordersmodel_product_ordersmodel_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=999999.99, max_digits=8),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
